[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm install && npm run build && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3001"
JWT_SECRET = "pokemon-super-secret-key-2024"
NEXT_PUBLIC_API_URL = "localhost:3001"
