# Backend service
[[services]]
name = "pokemon-center-backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
JWT_SECRET = "pokemon-super-secret-key-2024"

# Frontend service  
[[services]]
name = "pokemon-center-frontend"
source = "frontend"

[services.variables]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "${{services.pokemon-center-backend.url:3001}}"
